SELECT
	*
FROM
	ORDERS AS O
	INNER JOIN ORDER_DETAILS AS OD ON O.ORDER_ID = OD.ORDER_ID
	INNER JOIN PRODUCTS AS P ON OD.PRODUCT_ID = P.PRODUCT_ID
	INNER JOIN CUSTOMERS AS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE
	O.ORDER_ID = 10250